### ISSUE TITLE
Why reinvent the wheel? Please contribute here

### ISSUE THREAD

**Issue by tushar-semwal** [poga/awesome-federated-learning#2]
https://github.com/tushar-semwal/awesome-federated-computing

**Comment by poga** [comment]
The list started as a list of links related to federated learning. However, it evolved to include many related topics such as differential privacy, security and privacy issues in ML, and distributed learning.

I don't think we're actually "reinventing the wheel" here. Just different viewpoints.

**Comment by tushar-semwal** [comment]
Well, everyone always has a different "viewpoint", I believe. But, that is the whole point of collaboration where different views become one good project. Nonetheless, thanks for the quick response. Good luck. Cheers!

**Comment by poga** [comment]
I've added awesome-federated-computing to the list: https://github.com/poga/awesome-federated-learning/commit/cc963ecc9bbafce614fc0d408a8eda6eee5bd335
