### ISSUE TITLE
Add xaynet and Xayn AG

### ISSUE THREAD

**Issue by asmaier** [poga/awesome-federated-learning#9]
I suggest to add https://xaynet.webflow.io/  (Open source framework for federated learning in Rust) to the code section and the company behind the framework Xayn AG (https://www.xayn.com/ ) to the company section.

**Comment by poga** [comment]
Sure, can you submit a PR?

**Comment by asmaier** [comment]
I created PR  #10 .

**Comment by poga** [comment]
merged. Thanks!
